### ISSUE TITLE
Compile fails with MSVC

### ISSUE THREAD

**Issue by johnyyan** [Fumohouse/godot-luau-script#1]
this project is great, thanks for your work.
when i compile with scons, error output:
![image](https://user-images.githubusercontent.com/25659468/214550587-f6c62ecb-bb2a-42c6-8b51-c7e80588a109.png)
do we have build guide?

**Comment by voidedWarranties** [comment]
Hi! Thanks for your interest in this project.
Yes, things are still in an early stage right now. Please see the disclaimers in `README.md`.

This project is also completely undocumented - I'll try to fix that at some point in the near future.

That being said, I've worked out the build issues with MSVC in https://github.com/Fumohouse/godot-luau-script/commit/a2899d78208298bb34b8c3f644b78e50806e154c. Please let me know if you still have issues building.

If you have any questions, feel free to ask them [on Discord](https://discord.gg/X8Z3WzA6m6) or in a Github discussion.
