### ISSUE TITLE
_gdvirtual__get_language_call: Required virtual method ScriptExtension::_get_language must be overridden before calling.

### ISSUE THREAD

**Issue by iwishforducks** [Fumohouse/godot-luau-script#4]
`E 0:00:00:0562   _gdvirtual__get_language_call: Required virtual method ScriptExtension::_get_language must be overridden before calling.
  <C++ Source>   ./core/object/script_language_extension.h:106 @ _gdvirtual__get_language_call()
`

On Godot 4.1 beta-3. Happens in the mono version as well. The 4.1 RC-2 also seems to have the same error. I tried using the bin folder that comes with this, as well as building it on my own and it still has the same error regardless.

OS is Windows.

**Comment by voidedWarranties** [comment]
Hi, this is a known issue and I believe it's probably to do with Godot rather than this project.

The method is implemented, and scripts should run properly despite this error.

**Comment by iwishforducks** [comment]
Hey there, thanks for the quick reply. Unfortunately it doesn't seem like it's running scripts regardless, and it gives me this error when I run:

> E 0:00:05:0615   LuauScript::analyze: Failed to parse class: Could not find class table
>   <Luau Source>  testscript.lua:1 @ LuauScript::analyze()

This error in the editor every time it tries to parse the script:

> res://testscript.lua:1 - Failed to parse class: Could not find class table

Script:

```
local ClassTable = {}
local GodotClass = godotclass(ClassTable)

print("This is a test print.")

--- @registerMethod
function ClassTable._ready()
	print ("This is a test function.")
end

return GodotClass
```

(I'm not sure how I wasn't getting this error last night. Maybe I was. I apologize- I was running on fumes when I made this issue, haha.)

**Comment by voidedWarranties** [comment]
That script does not fully follow conventions for class registration, hence why `analyze` cannot find your class table. Namely, you are missing the `--- @class` annotation and `godotclass` should be `gdclass`.

An example class and fairly extensive documentation on how to make the analyzer happy are [here](https://fumohouse.github.io/gls-docs/usage/writing-scripts/idiomatic-class.html) and [here](https://fumohouse.github.io/gls-docs/usage/writing-scripts/class-registration.html), respectively.

Let me know if you still have issues.

**Comment by iwishforducks** [comment]
> Namely, you are missing the --- @class annotation and godotclass should be gdclass.

Whoops. I noticed the missing annotation this morning, but I would have never noticed the incorrect syntax. Thanks for the help. It's working just fine now! :)
