### ISSUE TITLE
Condition !mb is true

### ISSUE THREAD

**Issue by lefortune** [Fumohouse/godot-luau-script#5]
`E 0:00:03:0538   gdextension_classdb_get_method_bind: Condition "!mb" is true. Returning: nullptr
  <C++ Source>   core/extension/gdextension_interface.cpp:1055 @ gdextension_classdb_get_method_bind()
`
Repeats 58 times upon startup.

Version: Godot v4.1.1.stable.official [bd6af8e0e]
System: MacBook Air (M1, 2020) 

Steps to reproduce:
- have macOS 
- use it

**Comment by voidedWarranties** [comment]
Hi!
This happens since OpenXR is not present in macOS builds as of Godot 4.1.1. It will be present in Godot 4.2, but I've implemented a basic fix here in case of future issues.
